apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-credentials
  namespace: helixobs
type: Opaque
stringData:
  POSTGRES_USER:     helix
  POSTGRES_PASSWORD: helix
  POSTGRES_DB:       helixobs
