apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"otelTraceID"\s*:\s*"(\w+)"'
          url: "$${__value.raw}"
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: false
        customQuery: true
        query: '{helix_instrument_id=~".+"} | json | otel_trace_id = "${__trace.traceId}" | line_format `{{.level | upper}} {{.msg}}  [{{.logger}}] {{.src}}`'
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true

  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    url: db:5432
    user: helix
    editable: false
    secureJsonData:
      password: helix
    jsonData:
      database: helixobs
      sslmode: disable
      timescaledb: true
